### ISSUE TITLE
No sudo for installation?

### ISSUE THREAD

**Issue by RoryBarnes** [VirtualPlanetaryLaboratory/vplot#4]
Currently vplot must be installed as super-user, which some people don't want to do. Can it be installed in a way that doesn't require sudo, but still works with CI for vplanet checks?

**Comment by rodluger** [comment]
@RoryBarnes I don't think this is true. How are people installing it? It may be possible that `python setup.py install` requires permissions to access the anaconda distribution directory, which on the Astro linux machines is read-only for regular users if they're using the built-in conda. The workaround in that case is to run
```
python setup.py install --user
```
Let me know if that works. The same goes for `pip`:
```
pip install vplot --user
```

**Comment by RoryBarnes** [comment]
Resolved with PR #5.
